#!/bin/bash

if [[ "$1" == "--ff" ]]; then
	firefox &

elif [[ "$1" == "--dc" ]]; then
	discord &

elif [[ "$1" == "--tr" ]]; then
	kitty -d ~ &

elif [[ "$1" == "--fm" ]]; then
	thunar ~ &

elif [[ "$1" == "--cd" ]]; then
	code &

elif [[ "$1" == "--st" ]]; then
	xfce4-settings-manager &

fi