#!/bin/bash
spotify_title="$(playerctl --player=spotify metadata --format '{{ title }}')"
tmp_temp_path=/tmp/cover.png

artlink="$(playerctl -p spotify metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
curl -s "$artlink" --output "$tmp_temp_path"