#!/bin/sh

powermenu(){
    sh $HOME/.config/eww/popups/powermenu.sh
}

control() {
    LOCK_FILE="$HOME/.cache/bar-control.lock"
    EWW_BIN=`which eww`

    # Run eww daemon if not running
    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        ${EWW_BIN} -c $HOME/.config/eww/vertical-bar open control-panel
    else
        ${EWW_BIN} -c $HOME/.config/eww/vertical-bar close control-panel
        rm "$LOCK_FILE"
    fi
}

notification()
{
    LOCK_FILE="$HOME/.cache/bar-notification.lock"
    EWW_BIN=`which eww`

    # Run eww daemon if not running
    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        ${EWW_BIN} -c $HOME/.config/eww/vertical-bar open notification
    else
        ${EWW_BIN} -c $HOME/.config/eww/vertical-bar close notification
        rm "$LOCK_FILE"
    fi
}

if [[ "$1" = "--powermenu" ]]; then
    powermenu
elif [ "$1" = "--control" ]; then
    control
elif [ "$1" = "--notifs" ]; then
    notification
fi