#!/bin/sh

powermenu(){
    sh $HOME/.config/eww/popups/powermenu.sh
}

launcher() {
    LOCK_FILE="$HOME/.cache/bar-launcher.lock"
    EWW_BIN=`which eww`
    
    # Run eww daemon if not running
    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi
    
    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        sh $HOME/.config/eww/bottom-bar/scripts/search
        primary=`xrandr | grep -w connected | awk '{print $1}' | head -1`
        bspc monitor -f "$primary"
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar open launcher
    else
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar close launcher
        rm "$LOCK_FILE"
    fi
}

notification()
{
    LOCK_FILE="$HOME/.cache/bar-notification.lock"
    EWW_BIN=`which eww`
    
    # Run eww daemon if not running
    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi
    
    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar open notifs
    else
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar close notifs
        rm "$LOCK_FILE"
    fi
}

calendar()
{
    LOCK_FILE="$HOME/.cache/bar-calendar.lock"
    EWW_BIN=`which eww`
    
    # Run eww daemon if not running
    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi
    
    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar open calendar
    else
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar close calendar
        rm "$LOCK_FILE"
    fi
}



spotify()
{
    LOCK_FILE="$HOME/.cache/bar-spotify.lock"
    EWW_BIN=`which eww`
    
    # Run eww daemon if not running
    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi
    
    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar open spotify
    else
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar close spotify
        rm "$LOCK_FILE"
    fi
}

settings()
{
    LOCK_FILE="$HOME/.cache/bar-settings.lock"
    EWW_BIN=`which eww`
    
    # Run eww daemon if not running
    if [[ ! `pidof eww` ]]; then
        ${EWW_BIN} daemon
        sleep 1
    fi
    
    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar open settings
    else
        ${EWW_BIN} -c $HOME/.config/eww/bottom-bar close settings
        rm "$LOCK_FILE"
    fi
}


if [[ "$1" = "--powermenu" ]]; then
    powermenu
    elif [ "$1" = "--launcher" ]; then
    launcher
    elif [ "$1" = "--notifs" ]; then
    notification
    elif [ "$1" = "--spotify" ]; then
    spotify
    elif [ "$1" = "--calendar" ]; then
    calendar
    elif [ "$1" = "--settings" ]; then
    settings
fi