#!/bin/bash
# Get the coordinates of the active window's
#    top-left corner, and the window's size.
#    This excludes the window decoration.
x=0
y=0
w=0
h=0
eval $(xwininfo -name "stalonetray" |
    sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
    -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" \
    -e "s/^ \+Width: \+\([0-9]\+\).*/w=\1/p" \
    -e "s/^ \+Height: \+\([0-9]\+\).*/h=\1/p" )
echo $w