#!/bin/sh

workspaces() {
    
    # Id of workspaces, should be set in your $HOME/.config/bspwm/bspwmrc
    ws1=1
    ws2=2
    ws3=3
    ws4=4
    ws5=5
    ws6=6
    
    # Workspace icons
    wi1="󰈹"
    wi2="󰉋"
    wi3="󱂬"
    wi4="󰊤"
    wi5="󰓇"
    wi6="󰙯"
    
    # Unoccupied value
    un="0"
    
    # Returns id of desktop if occupied, nothing otherwise
    o1=$(bspc query -D -d .occupied --names | grep "$ws1" )
    o2=$(bspc query -D -d .occupied --names | grep "$ws2" )
    o3=$(bspc query -D -d .occupied --names | grep "$ws3" )
    o4=$(bspc query -D -d .occupied --names | grep "$ws4" )
    o5=$(bspc query -D -d .occupied --names | grep "$ws5" )
    o6=$(bspc query -D -d .occupied --names | grep "$ws6" )
    
    # Returns id of desktop if focused, nothing otherwise
    f1=$(bspc query -D -d focused --names | grep "$ws1" )
    f2=$(bspc query -D -d focused --names | grep "$ws2" )
    f3=$(bspc query -D -d focused --names | grep "$ws3" )
    f4=$(bspc query -D -d focused --names | grep "$ws4" )
    f5=$(bspc query -D -d focused --names | grep "$ws5" )
    f6=$(bspc query -D -d focused --names | grep "$ws6" )
    
    # How the classes of the workspaces work:
    # We set $un$ox$un$fx as the class for button x where x is the desktop number
    # We also display $wix as the icon for the button
    # If unoccupied and unfocused, the class would be 00
    # If occupied and unfocused, the class would be 0x0
    # If unoccupied and focused, the class would be 00x
    # If occupied and focused, the class would be 0x0x
    
    echo "(box :class \"works\" :orientation \"v\" :halign \"center\" :valign \"start\" (button :onclick \"bspc desktop -f $ws1\" :class \"$un$o1$un$f1\" \"$wi1\") (button :onclick \"bspc desktop -f $ws2\" :class \"$un$o2$un$f2\" \"$wi2\") (button :onclick \"bspc desktop -f $ws3\" :class \"$un$o3$un$f3\" \"$wi3\") (button :onclick \"bspc desktop -f $ws4\" :class \"$un$o4$un$f4\" \"$wi4\") (button :onclick \"bspc desktop -f $ws5\" :class \"$un$o5$un$f5\" \"$wi5\" ) (button :onclick \"bspc desktop -f $ws6\" :class \"$un$o6$un$f6\" \"$wi6\"))"
}

workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
    workspaces
done